airlines/urls.py
from django.urls import path

from . import views

app_name = "airlines"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:flight_id>", views.flight, name="flight"),
    path("<int:flight_id>/book", views.book, name="book")
]

demo/urls.py
from django.contrib import admin # type: ignore
from django.urls import path

urlpatterns = [
    path("admin/", admin.site.urls),
]

airlines/models.py
from django.db import models

# Create your models here.

airlines/views.py
from django.shortcuts import render

# Create your views here.

tasks/views.py
from django.shortcuts import render # type: ignore

# Create your views here.
tasks = ["foo", "bar", "sth"]


def add(request):
    if request.method == "POST":
        form = TaskForm(request.POST)
        if form.is_valid():
            tasks.appe
    return render(request, "tasks/add.html")

airlines/templates/airlines/flight.html
{% extends 'base.html' %}

{% block 'little' %}
Flight Detail
{% endblock %}

{% block 'content' %}
    <h1>Flight {{ flight.id }}</h1>
    <ul>
        <li>Origin: {{ flight.origin }}</li>
        <li>Destination: {{ flight.destination }}</li>
        <li>Duration: {{ flight.duration }}</li>
    </ul>

    <h2>Passengers:</h2>
    <ul>
        {% for passenger in flight.passengers.all %}
            <li>{{ passenger }}</li>
        {% endfor %}
    </ul>

    <h2>Add Passengers</h2>
    <form action="{% url 'airlines:book' flight.id %}" method="post">
        {% csrf_token %}
        <label for="name">Name:</label>
        <select name="passenger"
            {% for passenger in nonpassengers %}
                <option value="{{ passenger.id }}">{{ passenger }}</option>
            {% endfor %}
        </select>
        <button type="submit">Add Passenger</button>
    </form>
    
    <a href="{% url 'airlines:index' %}">Back to Flights</a>
{% endblock %}

tasks/templates/tasks/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Task</title>
</head>
<body>
    <h1>Add Task</h1>
    <form action="{% url 'add' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Add Task</button>
    </form>

    <br>
    <a href="{% url 'index' %}">Task List</a>
</body>
</html>

tasks/templates/tasks/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Task List</title>
</head>
<body>
    <h1>Task List</h1>
    <ul>
    {% for task in task %}
        <li>{{ task }}</li>
    {% empty %}
        <li>No Tasks found</li>
    {% endfor %}
    </ul>

    <a href="{% url 'add' %}">Add Task</a>
</body>
</html>